Demo: Trigger_Image.cpp
	g++ -g -o Trigger_Image Trigger_Image.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/armhf -L$(MVCAM_COMMON_RUNENV)/armhf -lMvCameraControl -lpthread
	

clean:
	rm Trigger_Image -rf
