Demo: ParametrizeCamera_FileAccess.cpp
	g++ -g -o ParametrizeCamera_FileAccess ParametrizeCamera_FileAccess.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/armhf -L$(MVCAM_COMMON_RUNENV)/armhf -lMvCameraControl -lpthread
	

clean:
	rm ParametrizeCamera_FileAccess -rf
