Demo: ImageProcess.cpp
	g++ -g -o ImageProcess ImageProcess.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/armhf -L$(MVCAM_COMMON_RUNENV)/armhf -lMvCameraControl 
	

clean:
	rm ImageProcess -rf
