Demo: GrabMultipleCamera.cpp
	g++ -g -o GrabMultipleCamera GrabMultipleCamera.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/armhf -L$(MVCAM_COMMON_RUNENV)/armhf -lMvCameraControl -lpthread
	

clean:
	rm GrabMultipleCamera -rf
