Demo: GrabImage.cpp
	g++ -g -o GrabImage GrabImage.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/armhf -L$(MVCAM_COMMON_RUNENV)/armhf -lMvCameraControl -lpthread
	

clean:
	rm GrabImage -rf
