Demo: Trigger_ImageCallback.cpp
	g++ -g -o Trigger_ImageCallback Trigger_ImageCallback.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/armhf -L$(MVCAM_COMMON_RUNENV)/armhf -lMvCameraControl -lpthread
	

clean:
	rm Trigger_ImageCallback -rf
